#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Viviane'
    hostname: ubuntu-desktop
    username: viviane
    password: '$y$j9T$9gKaOtwnGtcdIbrzB.uMx0$4bS3bYLLaksyHCQkxmvS3gnunbVtcfjYU6Iy9kAa/c'
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  storage:
    layout:
      name: lvm
    config:
      - type: disk
        id: disk-sda
        path: /dev/sda  # Substitua pelo nome correto do seu disco
        ptable: gpt
        wipe: superblock
      - type: partition
        id: partition-boot
        device: disk-sda
        size: 512M
        flag: boot
      - type: partition
        id: partition-root
        device: disk-sda
        size: 20G
      - type: partition
        id: partition-home
        device: disk-sda
        size: -1  # Usa o restante do espaço
      - type: format
        id: format-boot
        volume: partition-boot
        fstype: ext4
      - type: format
        id: format-root
        volume: partition-root
        fstype: ext4
      - type: format
        id: format-home
        volume: partition-home
        fstype: ext4
      - type: mount
        id: mount-boot
        device: format-boot
        path: /boot
      - type: mount
        id: mount-root
        device: format-root
        path: /
      - type: mount
        id: mount-home
        device: format-home
        path: /home
  packages:
    - libreoffice
    - gimp
    - git
    - wget
    - build-essential
    - python3
    - nodejs
    - docker
    - vim
    - curl
    - openssh-server
    - net-tools
    - nmap
    - htop
    - tmux
    - unzip
    - rsync
    - vlc
    - ffmpeg
    - audacity
    - thunderbird
    - evince
    - ufw
    - fail2ban
    - chromium-browser
    - firefox
    - gnome-tweaks
    - zsh
    - oh-my-zsh
    - ruby-full
    - maven
    - golang
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: maltego
      channel: stable
      classic: false
    - name: burp-suite
      channel: stable
      classic: false
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot

  # Seção late-commands
  late-commands:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y htop neofetch tmux curl git
    - chsh -s /usr/bin/zsh viviane
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    - git config --global user.name "Viviane"
    - git config --global user.email "vivianeaguiarc@outlook.com"
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh get-docker.sh
    - usermod -aG docker viviane
    - ufw allow ssh
    - ufw allow http
    - ufw allow https
    - ufw enable
    - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-archive-keyring.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
    - apt-get update && apt-get install -y code
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
    - apt-get install -y /tmp/chrome.deb
    - fallocate -l 2G /swapfile
    - chmod 600 /swapfile
    - mkswap /swapfile
    - swapon /swapfile
    - echo '/swapfile none swap sw 0 0' >> /etc/fstab
    - apt-get autoremove -y
    - apt-get clean
    - timedatectl set-timezone America/Sao_Paulo
    - apt-get install -y ntp
    - systemctl enable ntp
    - systemctl start ntp
    - apt-get install -y snapd
    - snap install spotify
    - snap install slack --classic
    - echo "alias ll='ls -la'" >> /home/viviane/.zshrc
    - echo "alias update='sudo apt-get update && sudo apt-get upgrade -y'" >> /home/viviane/.zshrc
    - apt-get install -y golang
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - curl -s "https://get.sdkman.io" | bash
    - sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
    - systemctl restart ssh